version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth-service
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kanban-net

volumes:
  pgdata:

networks:
  kanban-net:
      external: true
