spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: taskuser
    password: taskpass
  liquibase:
    change-log: classpath:/db/changelog/master.yml
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081