server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/auth/**
        - id: task-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/todo/**

